version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: |
          docker build -t aldaaa/karsajobs-ui:latest .
          docker tag aldaaa/karsajobs-ui:latest ghcr.io/aldaaaaa/a433-microservices/karsajobs-ui:latest
          echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin
          docker push ghcr.io/aldaaaaa/a433-microservices/karsajobs-ui:latest

workflows:
  version: 2
  karsajobs-ui:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile