version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run: hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin
          docker build -t aldaaa/karsajobs:latest .
          docker tag aldaaa/karsajobs:latest ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest
          docker push ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest

workflows:
  version: 2
  lint-test-and-build:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app