version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run: hadolint Dockerfile
      - run:
          name: Load SSH Key
          command: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t aldaaa/karsajobs:latest .
            docker tag aldaaa/karsajobs:latest ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest
            echo "$GHCR_TOKEN" | docker login ghcr.io -u aldaaaaa --password-stdin
            docker push ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest

workflows:
  version: 2
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app