name: Continuous Integration

on:
  push:
    branches:
      - karsajobs
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: |
          find . -name 'Dockerfile*' | xargs hadolint

  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Tests
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest .

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/aldaaaaa/a433-microservices/karsajobs-ui:latest .
