name: Continuous Integration

on:
  push:
    branches:
      - karsajobs
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: hadolint karsajobs/Dockerfile

  test-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run Unit Tests
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker Registry
        run: echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t aldaaa/karsajobs:latest .
          docker tag aldaaa/karsajobs:latest ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest
          docker push ghcr.io/aldaaaaa/a433-microservices/karsajobs:latest

  lint-dockerfile-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: hadolint karsajobs-ui/Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker Registry
        run: echo $GHCR_TOKEN | docker login ghcr.io -u aldaaaaa --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t aldaaa/karsajobs-ui:latest .
          docker tag aldaaa/karsajobs-ui:latest ghcr.io/aldaaaaa/a433-microservices/karsajobs-ui:latest
          docker push ghcr.io/aldaaaaa/a433-microservices/karsajobs-ui:latest
